In [ ]:
import numpy as np

In [ ]:
l1 = [i for i in range(10)]

In [ ]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(l1)

list

In [ ]:
np.array(l1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([[2,3,4],[5,6,7],[8,9,10]])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#linear spacing
np.linspace(0,1,5) #(start,end,count)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3,3))

array([[0.62970111, 0.0558722 , 0.09347216],
       [0.27849159, 0.61574529, 0.66792532],
       [0.51704802, 0.12294037, 0.87422997]])

In [ ]:
'''

class numpy -- parentclass
class random -- child class

    def random

    def randint

    def normal


'''


np.random.randint(0,10,(3,3))

array([[6, 3, 4],
       [7, 2, 5],
       [1, 8, 6]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x1 = np.random.randint(0,10,size=6)
x2 = np.random.randint(0,10,size=(3,4))
x3 = np.random.randint(0,10,size=(3,4,5))

In [ ]:
x1

array([0, 0, 1, 8, 9, 9])

In [ ]:
x2

array([[8, 0, 8, 5],
       [6, 6, 1, 6],
       [4, 8, 3, 6]])

In [ ]:
x3

array([[[0, 3, 0, 0, 2],
        [2, 1, 1, 8, 0],
        [8, 2, 1, 0, 9],
        [0, 7, 8, 1, 2]],

       [[6, 9, 1, 5, 0],
        [5, 0, 9, 2, 5],
        [1, 3, 5, 9, 3],
        [4, 6, 6, 6, 7]],

       [[9, 1, 9, 8, 4],
        [1, 3, 4, 2, 6],
        [8, 9, 8, 6, 8],
        [7, 2, 4, 1, 4]]])

In [ ]:
# to check the dimention of a array
x3.ndim

3

In [ ]:
x2.ndim

2

In [ ]:
x1.ndim

1

In [ ]:
x3.shape

(3, 4, 5)

In [ ]:
x2.shape

(3, 4)

In [ ]:
x1.shape

(6,)

In [ ]:
x3.size

60

In [ ]:
x2.size

12

In [ ]:
x1.size

6

In [ ]:
x1

array([0, 0, 1, 8, 9, 9])

In [ ]:
x1[0]

0

In [ ]:
x1[3]

8

In [ ]:
x1[-1]

9

In [ ]:
x1[-2]

9

In [ ]:
x2

array([[8, 0, 8, 5],
       [6, 6, 1, 6],
       [4, 8, 3, 6]])

In [ ]:
x2[0,0] #[rowindex,columnindex]

8

In [ ]:
x2[0,1]

0

In [ ]:
x2[0,0] = 12
x2

array([[12,  0,  8,  5],
       [ 6,  6,  1,  6],
       [ 4,  8,  3,  6]])

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [ ]:
'''

axis = 0 mean rows
axis = 1 mean column

'''
x.shape

(3,)

In [ ]:
y.shape

(3,)

In [ ]:
np.concatenate((x,y)) # default axis = 0

array([1, 2, 3, 4, 5, 6])

In [ ]:
x = x.reshape((3,1))
y = y.reshape((3,1))
np.concatenate([x,y],axis=1) # default axis = 0

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
grid = np.array([[[1,2,3],[4,5,6]]])
grid.shape

(1, 2, 3)

In [ ]:
np.concatenate((grid,grid),axis=1)

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]])

In [ ]:
np.concatenate((grid,grid),axis=1).shape

(1, 4, 3)

In [ ]:
grid

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
x = np.arange(3)

In [ ]:
x.shape

(3,)

In [210]:
np.vstack([x,grid]) #vstack - vertical stack

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [211]:
grid.shape

(2, 3)

In [213]:
np.vstack([x,grid.T])

array([[1, 2],
       [9, 6],
       [8, 5],
       [7, 4]])

In [214]:
grid.shape

(2, 3)

In [215]:
x = np.array([[99],[99]])

In [216]:
x.shape

(2, 1)

In [217]:
np.hstack([grid,x])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [218]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [219]:
np.hsplit(grid,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [220]:
np.hsplit(grid,[2])[0].shape

(4, 2)

In [221]:
np.vsplit(grid,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [222]:
x = np.arange(4)

In [223]:
np.add(x,5)

array([5, 6, 7, 8])

In [224]:
x = np.array([-1,2,-4,-7.8])
np.abs(x)

array([1. , 2. , 4. , 7.8])

In [225]:
x1 = np.linspace(0,np.pi,3)

In [226]:
x1

array([0.        , 1.57079633, 3.14159265])

In [227]:
np.sin(x1)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [228]:
np.cos(x1)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [229]:
np.tan(x1)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [230]:
x = np.array([4,7,2])
np.exp(x)

array([  54.59815003, 1096.63315843,    7.3890561 ])

In [231]:
np.power(2,x)

array([ 16, 128,   4])

In [232]:
np.power(3,x)

array([  81, 2187,    9])

In [233]:
x = np.array([2,4,6,8])
np.log(x)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154])

In [234]:
np.log2(x)

array([1.       , 2.       , 2.5849625, 3.       ])

In [235]:
np.log10(x)

array([0.30103   , 0.60205999, 0.77815125, 0.90308999])

In [236]:
x = np.random.randn(100)

In [237]:
#summ of all the elements in the numpy array
np.sum(x)

5.195326110493595

In [238]:
np.max(x)

2.8552907887317875

In [239]:
np.min(x)

-2.3823289995711683

TO UPLOAD FILE TO COLAB

In [240]:
from google.colab import files
uploaded = files.upload()

Saving president_heights.csv to president_heights (1).csv


In [246]:
import pandas as pd

df = pd.read_csv('president_heights.csv')

# read the csv files - pandas


In [248]:
df.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [247]:
df.shape

(44, 3)

In [ ]:
heights = df['height(cm)'].values

In [ ]:
heights

In [ ]:
np.max(heights)

In [ ]:
np.mean(heights)

In [ ]:
np.std(heights)

In [ ]:
np.median(heights)

In [ ]:
import matplotlib.pyplot as plt


plt.

#Broadcasting

In [ ]:
a = np.array([4,5,7])
b = np.ones((3,3))

In [ ]:
a

In [ ]:
b

In [ ]:
np.add(a,b)

In [ ]:
'''
3x1
3x3

Broadcasting

4 6 7
4 6 7
4 6 7

'''

#Double-click(or enter) to edit



In [ ]:
x = np.random.random((10,2))

In [ ]:
x

In [ ]:
x.mean()

In [ ]:
np.std(x)

In [ ]:
xcententer = x - np.mean(x)

In [ ]:
xno

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
df

In [ ]:
plt.hist(rainfall)

In [ ]:
np.sum((rainfall > 100) & (rainfall < 200))

NameError: ignored

In [ ]:
x = np.array([4,6,8,9])

In [ ]:
np.max(x)

3

In [ ]:
np.sort(x)

array([1, 2, 3])

In [ ]:
np.argmax(x) # returns the position of maximum value in the numpy array

2