In [1]:
import numpy as np

In [2]:
l1 = [1,2,3]


In [3]:
a = np.array(l1)

In [4]:
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
l1 = [1,2,3,5,6,7]

In [7]:
a = np.array(l1)

In [8]:
a

array([1, 2, 3, 5, 6, 7])

In [9]:
a.shape

(6,)

In [ ]:
x = np.array([1,2,3])
y = 


In [ ]:
x = np.array[8,9,10]
y =np.array[13,14,15]

In [13]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
x.shape

(3, 3)

In [18]:
x = np.array ([[1,2],[4,5],[7,8]])

In [19]:
x = np.array ([[1,2],[2,4],[5,6]])

In [20]:
x

array([[1, 2],
       [2, 4],
       [5, 6]])

In [21]:
x.shape

(3, 2)

In [24]:
x = [i for i in range(0,10)]

In [25]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
x = np.arange(1,10)

In [28]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x = np.arange(10,20,2)

In [30]:
x

array([10, 12, 14, 16, 18])

In [31]:
x = np.arange(0.5,10.4,0.8)

In [32]:
x

array([ 0.5,  1.3,  2.1,  2.9,  3.7,  4.5,  5.3,  6.1,  6.9,  7.7,  8.5,
        9.3, 10.1])

In [33]:
x = np.arange(0.5,10.4,0.8,int)

In [34]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])